<?php

namespace Database\Seeders;

use App\Models\Airport;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AirportSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //DB::table('airports')->truncate();

        $airports = [
            ['name' => 'Priština International Airport',  'iso_country' => 'XK', 'iso_region' => 'XK-01', 'iata_code' => 'PRN', ],
            ['name' => 'Edmonton International Airport',  'iso_country' => 'CA', 'iso_region' => 'CA-AB', 'iata_code' => 'YEG', ],
            ['name' => 'Halifax / Stanfield International Airport',  'iso_country' => 'CA', 'iso_region' => 'CA-NS', 'iata_code' => 'YHZ', ],
            ['name' => 'Ottawa Macdonald-Cartier International Airport',  'iso_country' => 'CA', 'iso_region' => 'CA-ON', 'iata_code' => 'YOW', ],
            ['name' => 'Montreal / Pierre Elliott Trudeau International Airport',  'iso_country' => 'CA', 'iso_region' => 'CA-QC', 'iata_code' => 'YUL', ],
            ['name' => 'Vancouver International Airport',  'iso_country' => 'CA', 'iso_region' => 'CA-BC', 'iata_code' => 'YVR', ],
            ['name' => 'Winnipeg / James Armstrong Richardson International Airport',  'iso_country' => 'CA', 'iso_region' => 'CA-MB', 'iata_code' => 'YWG', ],
            ['name' => 'Calgary International Airport',  'iso_country' => 'CA', 'iso_region' => 'CA-AB', 'iata_code' => 'YYC', ],
            ['name' => 'Victoria International Airport',  'iso_country' => 'CA', 'iso_region' => 'CA-BC', 'iata_code' => 'YYJ', ],
            ['name' => 'St. John\ns International Airport',  'iso_country' => 'CA', 'iso_region' => 'CA-NL', 'iata_code' => 'YYT', ],
            ['name' => 'Lester B. Pearson International Airport',  'iso_country' => 'CA', 'iso_region' => 'CA-ON', 'iata_code' => 'YYZ', ],
            ['name' => 'Brussels Airport',  'iso_country' => 'BE', 'iso_region' => 'BE-BRU', 'iata_code' => 'BRU', ],
            ['name' => 'Brussels South Charleroi Airport',  'iso_country' => 'BE', 'iso_region' => 'BE-WHT', 'iata_code' => 'CRL', ],
            ['name' => 'Liège Airport',  'iso_country' => 'BE', 'iso_region' => 'BE-WLG', 'iata_code' => 'LGG', ],
            ['name' => 'Berlin Brandenburg Airport',  'iso_country' => 'DE', 'iso_region' => 'DE-BR', 'iata_code' => 'BER', ],
            ['name' => 'Dresden Airport',  'iso_country' => 'DE', 'iso_region' => 'DE-SN', 'iata_code' => 'DRS', ],
            ['name' => 'Frankfurt am Main Airport',  'iso_country' => 'DE', 'iso_region' => 'DE-HE', 'iata_code' => 'FRA', ],
            ['name' => 'Münster Osnabrück Airport',  'iso_country' => 'DE', 'iso_region' => 'DE-NW', 'iata_code' => 'FMO', ],
            ['name' => 'Hamburg Airport',  'iso_country' => 'DE', 'iso_region' => 'DE-HH', 'iata_code' => 'HAM', ],
            ['name' => 'Cologne Bonn Airport',  'iso_country' => 'DE', 'iso_region' => 'DE-NW', 'iata_code' => 'CGN', ],
            ['name' => 'Düsseldorf Airport',  'iso_country' => 'DE', 'iso_region' => 'DE-NW', 'iata_code' => 'DUS', ],
            ['name' => 'Munich Airport',  'iso_country' => 'DE', 'iso_region' => 'DE-BY', 'iata_code' => 'MUC', ],
            ['name' => 'Nuremberg Airport',  'iso_country' => 'DE', 'iso_region' => 'DE-BY', 'iata_code' => 'NUE', ],
            ['name' => 'Leipzig/Halle Airport',  'iso_country' => 'DE', 'iso_region' => 'DE-SN', 'iata_code' => 'LEJ', ],
            ['name' => 'Stuttgart Airport',  'iso_country' => 'DE', 'iso_region' => 'DE-BW', 'iata_code' => 'STR', ],
            ['name' => 'Berlin-Tegel Airport',  'iso_country' => 'DE', 'iso_region' => 'DE-BE', 'iata_code' => 'TXL', ],
            ['name' => 'Hannover Airport',  'iso_country' => 'DE', 'iso_region' => 'DE-NI', 'iata_code' => 'HAJ', ],
            ['name' => 'Bremen Airport',  'iso_country' => 'DE', 'iso_region' => 'DE-HB', 'iata_code' => 'BRE', ],
            ['name' => 'Dortmund Airport',  'iso_country' => 'DE', 'iso_region' => 'DE-NW', 'iata_code' => 'DTM', ],
            ['name' => 'Karlsruhe Baden-Baden Airport',  'iso_country' => 'DE', 'iso_region' => 'DE-BW', 'iata_code' => 'FKB', ],
            ['name' => 'Lennart Meri Tallinn Airport',  'iso_country' => 'EE', 'iso_region' => 'EE-37', 'iata_code' => 'TLL', ],
            ['name' => 'Helsinki Vantaa Airport',  'iso_country' => 'FI', 'iso_region' => 'FI-18', 'iata_code' => 'HEL', ],
            ['name' => 'Belfast International Airport',  'iso_country' => 'GB', 'iso_region' => 'GB-NIR', 'iata_code' => 'BFS', ],
            ['name' => 'George Best Belfast City Airport',  'iso_country' => 'GB', 'iso_region' => 'GB-NIR', 'iata_code' => 'BHD', ],
            ['name' => 'Birmingham International Airport',  'iso_country' => 'GB', 'iso_region' => 'GB-ENG', 'iata_code' => 'BHX', ],
            ['name' => 'Manchester Airport',  'iso_country' => 'GB', 'iso_region' => 'GB-ENG', 'iata_code' => 'MAN', ],
            ['name' => 'Robin Hood Doncaster Sheffield Airport',  'iso_country' => 'GB', 'iso_region' => 'GB-ENG', 'iata_code' => 'DSA', ],
            ['name' => 'Cardiff International Airport',  'iso_country' => 'GB', 'iso_region' => 'GB-WLS', 'iata_code' => 'CWL', ],
            ['name' => 'Bristol Airport',  'iso_country' => 'GB', 'iso_region' => 'GB-ENG', 'iata_code' => 'BRS', ],
            ['name' => 'Liverpool John Lennon Airport',  'iso_country' => 'GB', 'iso_region' => 'GB-ENG', 'iata_code' => 'LPL', ],
            ['name' => 'London Luton Airport',  'iso_country' => 'GB', 'iso_region' => 'GB-ENG', 'iata_code' => 'LTN', ],
            ['name' => 'Bournemouth Airport',  'iso_country' => 'GB', 'iso_region' => 'GB-ENG', 'iata_code' => 'BOH', ],
            ['name' => 'Southampton Airport',  'iso_country' => 'GB', 'iso_region' => 'GB-ENG', 'iata_code' => 'SOU', ],
            ['name' => 'London Gatwick Airport',  'iso_country' => 'GB', 'iso_region' => 'GB-ENG', 'iata_code' => 'LGW', ],
            ['name' => 'London Heathrow Airport',  'iso_country' => 'GB', 'iso_region' => 'GB-ENG', 'iata_code' => 'LHR', ],
            ['name' => 'Leeds Bradford Airport',  'iso_country' => 'GB', 'iso_region' => 'GB-ENG', 'iata_code' => 'LBA', ],
            ['name' => 'Newcastle Airport',  'iso_country' => 'GB', 'iso_region' => 'GB-ENG', 'iata_code' => 'NCL', ],
            ['name' => 'East Midlands Airport',  'iso_country' => 'GB', 'iso_region' => 'GB-ENG', 'iata_code' => 'EMA', ],
            ['name' => 'Aberdeen Dyce Airport',  'iso_country' => 'GB', 'iso_region' => 'GB-SCT', 'iata_code' => 'ABZ', ],
            ['name' => 'Glasgow International Airport',  'iso_country' => 'GB', 'iso_region' => 'GB-SCT', 'iata_code' => 'GLA', ],
            ['name' => 'Edinburgh Airport',  'iso_country' => 'GB', 'iso_region' => 'GB-SCT', 'iata_code' => 'EDI', ],
            ['name' => 'Norwich International Airport',  'iso_country' => 'GB', 'iso_region' => 'GB-ENG', 'iata_code' => 'NWI', ],
            ['name' => 'London Stansted Airport',  'iso_country' => 'GB', 'iso_region' => 'GB-ENG', 'iata_code' => 'STN', ],
            ['name' => 'Exeter International Airport',  'iso_country' => 'GB', 'iso_region' => 'GB-ENG', 'iata_code' => 'EXT', ],
            ['name' => 'RAF Lakenheath',  'iso_country' => 'GB', 'iso_region' => 'GB-ENG', 'iata_code' => 'LKZ', ],
            ['name' => 'RAF Mildenhall',  'iso_country' => 'GB', 'iso_region' => 'GB-ENG', 'iata_code' => 'MHZ', ],
            ['name' => 'RAF Fairford',  'iso_country' => 'GB', 'iso_region' => 'GB-ENG', 'iata_code' => 'FFD', ],
            ['name' => 'RAF Brize Norton',  'iso_country' => 'GB', 'iso_region' => 'GB-ENG', 'iata_code' => 'BZZ', ],
            ['name' => 'Amsterdam Airport Schiphol',  'iso_country' => 'NL', 'iso_region' => 'NL-NH', 'iata_code' => 'AMS', ],
            ['name' => 'Eindhoven Airport',  'iso_country' => 'NL', 'iso_region' => 'NL-NB', 'iata_code' => 'EIN', ],
            ['name' => 'Cork Airport',  'iso_country' => 'IE', 'iso_region' => 'IE-C', 'iata_code' => 'ORK', ],
            ['name' => 'Dublin Airport',  'iso_country' => 'IE', 'iso_region' => 'IE-D', 'iata_code' => 'DUB', ],
            ['name' => 'Shannon Airport',  'iso_country' => 'IE', 'iso_region' => 'IE-CE', 'iata_code' => 'SNN', ],
            ['name' => 'Billund Airport',  'iso_country' => 'DK', 'iso_region' => 'DK-83', 'iata_code' => 'BLL', ],
            ['name' => 'Copenhagen Kastrup Airport',  'iso_country' => 'DK', 'iso_region' => 'DK-84', 'iata_code' => 'CPH', ],
            ['name' => 'Aalborg Airport',  'iso_country' => 'DK', 'iso_region' => 'DK-81', 'iata_code' => 'AAL', ],
            ['name' => 'Luxembourg-Findel International Airport',  'iso_country' => 'LU', 'iso_region' => 'LU-L', 'iata_code' => 'LUX', ],
            ['name' => 'Bodø Airport',  'iso_country' => 'NO', 'iso_region' => 'NO-18', 'iata_code' => 'BOO', ],
            ['name' => 'Bergen Airport Flesland',  'iso_country' => 'NO', 'iso_region' => 'NO-12', 'iata_code' => 'BGO', ],
            ['name' => 'Oslo Gardermoen Airport',  'iso_country' => 'NO', 'iso_region' => 'NO-02', 'iata_code' => 'OSL', ],
            ['name' => 'Tromsø Airport',  'iso_country' => 'NO', 'iso_region' => 'NO-19', 'iata_code' => 'TOS', ],
            ['name' => 'Trondheim Airport Værnes',  'iso_country' => 'NO', 'iso_region' => 'NO-17', 'iata_code' => 'TRD', ],
            ['name' => 'Stavanger Airport Sola',  'iso_country' => 'NO', 'iso_region' => 'NO-11', 'iata_code' => 'SVG', ],
            ['name' => 'Gdańsk Lech Wałęsa Airport',  'iso_country' => 'PL', 'iso_region' => 'PL-PM', 'iata_code' => 'GDN', ],
            ['name' => 'Kraków John Paul II International Airport',  'iso_country' => 'PL', 'iso_region' => 'PL-MA', 'iata_code' => 'KRK', ],
            ['name' => 'Katowice International Airport',  'iso_country' => 'PL', 'iso_region' => 'PL-SL', 'iata_code' => 'KTW', ],
            ['name' => 'Modlin Airport',  'iso_country' => 'PL', 'iso_region' => 'PL-MZ', 'iata_code' => 'WMI', ],
            ['name' => 'Poznań-Ławica Airport',  'iso_country' => 'PL', 'iso_region' => 'PL-WP', 'iata_code' => 'POZ', ],
            ['name' => 'Warsaw Chopin Airport',  'iso_country' => 'PL', 'iso_region' => 'PL-MZ', 'iata_code' => 'WAW', ],
            ['name' => 'Copernicus Wrocław Airport',  'iso_country' => 'PL', 'iso_region' => 'PL-DS', 'iata_code' => 'WRO', ],
            ['name' => 'Gothenburg-Landvetter Airport',  'iso_country' => 'SE', 'iso_region' => 'SE-Q', 'iata_code' => 'GOT', ],
            ['name' => 'Malmö Sturup Airport',  'iso_country' => 'SE', 'iso_region' => 'SE-M', 'iata_code' => 'MMX', ],
            ['name' => 'Luleå Airport',  'iso_country' => 'SE', 'iso_region' => 'SE-BD', 'iata_code' => 'LLA', ],
            ['name' => 'Stockholm-Arlanda Airport',  'iso_country' => 'SE', 'iso_region' => 'SE-AB', 'iata_code' => 'ARN', ],
            ['name' => 'Ramstein Air Base',  'iso_country' => 'DE', 'iso_region' => 'DE-RP', 'iata_code' => 'RMS', ],
            ['name' => 'Riga International Airport',  'iso_country' => 'LV', 'iso_region' => 'LV-RIX', 'iata_code' => 'RIX', ],
            ['name' => 'Vilnius International Airport',  'iso_country' => 'LT', 'iso_region' => 'LT-VL', 'iata_code' => 'VNO', ],
            ['name' => 'La Palma Airport',  'iso_country' => 'ES', 'iso_region' => 'ES-CN', 'iata_code' => 'SPC', ],
            ['name' => 'Gran Canaria Airport',  'iso_country' => 'ES', 'iso_region' => 'ES-CN', 'iata_code' => 'LPA', ],
            ['name' => 'Tenerife South Airport',  'iso_country' => 'ES', 'iso_region' => 'ES-CN', 'iata_code' => 'TFS', ],
            ['name' => 'Tenerife Norte Airport',  'iso_country' => 'ES', 'iso_region' => 'ES-CN', 'iata_code' => 'TFN', ],
            ['name' => 'Albuquerque International Sunport',  'iso_country' => 'US', 'iso_region' => 'US-NM', 'iata_code' => 'ABQ', ],
            ['name' => 'Joint Base Andrews',  'iso_country' => 'US', 'iso_region' => 'US-MD', 'iata_code' => 'ADW', ],
            ['name' => 'Fort Worth Alliance Airport',  'iso_country' => 'US', 'iso_region' => 'US-TX', 'iata_code' => 'AFW', ],
            ['name' => 'Augusta Regional At Bush Field',  'iso_country' => 'US', 'iso_region' => 'US-GA', 'iata_code' => 'AGS', ],
            ['name' => 'Rick Husband Amarillo International Airport',  'iso_country' => 'US', 'iso_region' => 'US-TX', 'iata_code' => 'AMA', ],
            ['name' => 'Hartsfield Jackson Atlanta International Airport',  'iso_country' => 'US', 'iso_region' => 'US-GA', 'iata_code' => 'ATL', ],
            ['name' => 'Austin Bergstrom International Airport',  'iso_country' => 'US', 'iso_region' => 'US-TX', 'iata_code' => 'AUS', ],
            ['name' => 'Asheville Regional Airport',  'iso_country' => 'US', 'iso_region' => 'US-NC', 'iata_code' => 'AVL', ],
            ['name' => 'Beale Air Force Base',  'iso_country' => 'US', 'iso_region' => 'US-CA', 'iata_code' => 'BAB', ],
            ['name' => 'Barksdale Air Force Base',  'iso_country' => 'US', 'iso_region' => 'US-LA', 'iata_code' => 'BAD', ],
            ['name' => 'Bradley International Airport',  'iso_country' => 'US', 'iso_region' => 'US-CT', 'iata_code' => 'BDL', ],
            ['name' => 'Boeing Field King County International Airport',  'iso_country' => 'US', 'iso_region' => 'US-WA', 'iata_code' => 'BFI', ],
            ['name' => 'Bangor International Airport',  'iso_country' => 'US', 'iso_region' => 'US-ME', 'iata_code' => 'BGR', ],
            ['name' => 'Birmingham-Shuttlesworth International Airport',  'iso_country' => 'US', 'iso_region' => 'US-AL', 'iata_code' => 'BHM', ],
            ['name' => 'Billings Logan International Airport',  'iso_country' => 'US', 'iso_region' => 'US-MT', 'iata_code' => 'BIL', ],
            ['name' => 'Scott AFB/Midamerica Airport',  'iso_country' => 'US', 'iso_region' => 'US-IL', 'iata_code' => 'BLV', ],
            ['name' => 'Central Illinois Regional Airport at Bloomington-Normal',  'iso_country' => 'US', 'iso_region' => 'US-IL', 'iata_code' => 'BMI', ],
            ['name' => 'Nashville International Airport',  'iso_country' => 'US', 'iso_region' => 'US-TN', 'iata_code' => 'BNA', ],
            ['name' => 'Boise Air Terminal/Gowen Field',  'iso_country' => 'US', 'iso_region' => 'US-ID', 'iata_code' => 'BOI', ],
            ['name' => 'General Edward Lawrence Logan International Airport',  'iso_country' => 'US', 'iso_region' => 'US-MA', 'iata_code' => 'BOS', ],
            ['name' => 'Buffalo Niagara International Airport',  'iso_country' => 'US', 'iso_region' => 'US-NY', 'iata_code' => 'BUF', ],
            ['name' => 'Baltimore/Washington International Thurgood Marshall Airport',  'iso_country' => 'US', 'iso_region' => 'US-MD', 'iata_code' => 'BWI', ],
            ['name' => 'Columbia Metropolitan Airport',  'iso_country' => 'US', 'iso_region' => 'US-SC', 'iata_code' => 'CAE', ],
            ['name' => 'Columbus Air Force Base',  'iso_country' => 'US', 'iso_region' => 'US-MS', 'iata_code' => 'CBM', ],
            ['name' => 'Lovell Field',  'iso_country' => 'US', 'iso_region' => 'US-TN', 'iata_code' => 'CHA', ],
            ['name' => 'Charleston Air Force Base-International Airport',  'iso_country' => 'US', 'iso_region' => 'US-SC', 'iata_code' => 'CHS', ],
            ['name' => 'The Eastern Iowa Airport',  'iso_country' => 'US', 'iso_region' => 'US-IA', 'iata_code' => 'CID', ],
            ['name' => 'Cleveland Hopkins International Airport',  'iso_country' => 'US', 'iso_region' => 'US-OH', 'iata_code' => 'CLE', ],
            ['name' => 'Charlotte Douglas International Airport',  'iso_country' => 'US', 'iso_region' => 'US-NC', 'iata_code' => 'CLT', ],
            ['name' => 'John Glenn Columbus International Airport',  'iso_country' => 'US', 'iso_region' => 'US-OH', 'iata_code' => 'CMH', ],
            ['name' => 'City of Colorado Springs Municipal Airport',  'iso_country' => 'US', 'iso_region' => 'US-CO', 'iata_code' => 'COS', ],
            ['name' => 'Corpus Christi International Airport',  'iso_country' => 'US', 'iso_region' => 'US-TX', 'iata_code' => 'CRP', ],
            ['name' => 'Yeager Airport',  'iso_country' => 'US', 'iso_region' => 'US-WV', 'iata_code' => 'CRW', ],
            ['name' => 'Cincinnati Northern Kentucky International Airport',  'iso_country' => 'US', 'iso_region' => 'US-KY', 'iata_code' => 'CVG', ],
            ['name' => 'Cannon Air Force Base',  'iso_country' => 'US', 'iso_region' => 'US-NM', 'iata_code' => 'CVS', ],
            ['name' => 'Daytona Beach International Airport',  'iso_country' => 'US', 'iso_region' => 'US-FL', 'iata_code' => 'DAB', ],
            ['name' => 'Dallas Love Field',  'iso_country' => 'US', 'iso_region' => 'US-TX', 'iata_code' => 'DAL', ],
            ['name' => 'James M Cox Dayton International Airport',  'iso_country' => 'US', 'iso_region' => 'US-OH', 'iata_code' => 'DAY', ],
            ['name' => 'Dubuque Regional Airport',  'iso_country' => 'US', 'iso_region' => 'US-IA', 'iata_code' => 'DBQ', ],
            ['name' => 'Ronald Reagan Washington National Airport',  'iso_country' => 'US', 'iso_region' => 'US-DC', 'iata_code' => 'DCA', ],
            ['name' => 'Denver International Airport',  'iso_country' => 'US', 'iso_region' => 'US-CO', 'iata_code' => 'DEN', ],
            ['name' => 'Dallas Fort Worth International Airport',  'iso_country' => 'US', 'iso_region' => 'US-TX', 'iata_code' => 'DFW', ],
            ['name' => 'DLF Airport',  'iso_country' => 'US', 'iso_region' => 'US-TX', 'iata_code' => 'DLF', ],
            ['name' => 'Duluth International Airport',  'iso_country' => 'US', 'iso_region' => 'US-MN', 'iata_code' => 'DLH', ],
            ['name' => 'Dover Air Force Base',  'iso_country' => 'US', 'iso_region' => 'US-DE', 'iata_code' => 'DOV', ],
            ['name' => 'Des Moines International Airport',  'iso_country' => 'US', 'iso_region' => 'US-IA', 'iata_code' => 'DSM', ],
            ['name' => 'Detroit Metropolitan Wayne County Airport',  'iso_country' => 'US', 'iso_region' => 'US-MI', 'iata_code' => 'DTW', ],
            ['name' => 'Dyess Air Force Base',  'iso_country' => 'US', 'iso_region' => 'US-TX', 'iata_code' => 'DYS', ],
            ['name' => 'Edwards Air Force Base',  'iso_country' => 'US', 'iso_region' => 'US-CA', 'iata_code' => 'EDW', ],
            ['name' => 'Vance Air Force Base',  'iso_country' => 'US', 'iso_region' => 'US-OK', 'iata_code' => 'END', ],
            ['name' => 'Erie International Tom Ridge Field',  'iso_country' => 'US', 'iso_region' => 'US-PA', 'iata_code' => 'ERI', ],
            ['name' => 'Newark Liberty International Airport',  'iso_country' => 'US', 'iso_region' => 'US-NJ', 'iata_code' => 'EWR', ],
            ['name' => 'Wright-Patterson Air Force Base',  'iso_country' => 'US', 'iso_region' => 'US-OH', 'iata_code' => 'FFO', ],
            ['name' => 'Fort Lauderdale Hollywood International Airport',  'iso_country' => 'US', 'iso_region' => 'US-FL', 'iata_code' => 'FLL', ],
            ['name' => 'Fort Smith Regional Airport',  'iso_country' => 'US', 'iso_region' => 'US-AR', 'iata_code' => 'FSM', ],
            ['name' => 'Fort Worth Meacham International Airport',  'iso_country' => 'US', 'iso_region' => 'US-TX', 'iata_code' => 'FTW', ],
            ['name' => 'Fort Wayne International Airport',  'iso_country' => 'US', 'iso_region' => 'US-IN', 'iata_code' => 'FWA', ],
            ['name' => 'Spokane International Airport',  'iso_country' => 'US', 'iso_region' => 'US-WA', 'iata_code' => 'GEG', ],
            ['name' => 'Gulfport Biloxi International Airport',  'iso_country' => 'US', 'iso_region' => 'US-MS', 'iata_code' => 'GPT', ],
            ['name' => 'Austin Straubel International Airport',  'iso_country' => 'US', 'iso_region' => 'US-WI', 'iata_code' => 'GRB', ],
            ['name' => 'Seymour Johnson Air Force Base',  'iso_country' => 'US', 'iso_region' => 'US-NC', 'iata_code' => 'GSB', ],
            ['name' => 'Piedmont Triad International Airport',  'iso_country' => 'US', 'iso_region' => 'US-NC', 'iata_code' => 'GSO', ],
            ['name' => 'Greenville Spartanburg International Airport',  'iso_country' => 'US', 'iso_region' => 'US-SC', 'iata_code' => 'GSP', ],
            ['name' => 'Grissom Air Reserve Base',  'iso_country' => 'US', 'iso_region' => 'US-IN', 'iata_code' => 'GUS', ],
            ['name' => 'Range Regional Airport',  'iso_country' => 'US', 'iso_region' => 'US-MN', 'iata_code' => 'HIB', ],
            ['name' => 'Holloman Air Force Base',  'iso_country' => 'US', 'iso_region' => 'US-NM', 'iata_code' => 'HMN', ],
            ['name' => 'William P Hobby Airport',  'iso_country' => 'US', 'iso_region' => 'US-TX', 'iata_code' => 'HOU', ],
            ['name' => 'Huntsville International Carl T Jones Field',  'iso_country' => 'US', 'iso_region' => 'US-AL', 'iata_code' => 'HSV', ],
            ['name' => 'Tri-State/Milton J. Ferguson Field',  'iso_country' => 'US', 'iso_region' => 'US-WV', 'iata_code' => 'HTS', ],
            ['name' => 'Washington Dulles International Airport',  'iso_country' => 'US', 'iso_region' => 'US-VA', 'iata_code' => 'IAD', ],
            ['name' => 'George Bush Inte Airport',  'iso_country' => 'US', 'iso_region' => 'US-TX', 'iata_code' => 'IAH', ],
            ['name' => 'Wichita Eisenhower National Airport',  'iso_country' => 'US', 'iso_region' => 'US-KS', 'iata_code' => 'ICT', ],
            ['name' => 'Indianapolis International Airport',  'iso_country' => 'US', 'iso_region' => 'US-IN', 'iata_code' => 'IND', ],
            ['name' => 'Jackson-Medgar Wiley Evers International Airport',  'iso_country' => 'US', 'iso_region' => 'US-MS', 'iata_code' => 'JAN', ],
            ['name' => 'Jacksonville International Airport',  'iso_country' => 'US', 'iso_region' => 'US-FL', 'iata_code' => 'JAX', ],
            ['name' => 'John F Kennedy International Airport',  'iso_country' => 'US', 'iso_region' => 'US-NY', 'iata_code' => 'JFK', ],
            ['name' => 'Joplin Regional Airport',  'iso_country' => 'US', 'iso_region' => 'US-MO', 'iata_code' => 'JLN', ],
            ['name' => 'McCarran International Airport',  'iso_country' => 'US', 'iso_region' => 'US-NV', 'iata_code' => 'LAS', ],
            ['name' => 'Los Angeles International Airport',  'iso_country' => 'US', 'iso_region' => 'US-CA', 'iata_code' => 'LAX', ],
            ['name' => 'Lubbock Preston Smith International Airport',  'iso_country' => 'US', 'iso_region' => 'US-TX', 'iata_code' => 'LBB', ],
            ['name' => 'Rickenbacker International Airport',  'iso_country' => 'US', 'iso_region' => 'US-OH', 'iata_code' => 'LCK', ],
            ['name' => 'Blue Grass Airport',  'iso_country' => 'US', 'iso_region' => 'US-KY', 'iata_code' => 'LEX', ],
            ['name' => 'Langley Air Force Base',  'iso_country' => 'US', 'iso_region' => 'US-VA', 'iata_code' => 'LFI', ],
            ['name' => 'Lafayette Regional Airport',  'iso_country' => 'US', 'iso_region' => 'US-LA', 'iata_code' => 'LFT', ],
            ['name' => 'La Guardia Airport',  'iso_country' => 'US', 'iso_region' => 'US-NY', 'iata_code' => 'LGA', ],
            ['name' => 'Bill & Hillary Clinton National Airport/Adams Field',  'iso_country' => 'US', 'iso_region' => 'US-AR', 'iata_code' => 'LIT', ],
            ['name' => 'Altus Air Force Base',  'iso_country' => 'US', 'iso_region' => 'US-OK', 'iata_code' => 'LTS', ],
            ['name' => 'Luke Air Force Base',  'iso_country' => 'US', 'iso_region' => 'US-AZ', 'iata_code' => 'LUF', ],
            ['name' => 'MBS International Airport',  'iso_country' => 'US', 'iso_region' => 'US-MI', 'iata_code' => 'MBS', ],
            ['name' => 'Mac Dill Air Force Base',  'iso_country' => 'US', 'iso_region' => 'US-FL', 'iata_code' => 'MCF', ],
            ['name' => 'Kansas City International Airport',  'iso_country' => 'US', 'iso_region' => 'US-MO', 'iata_code' => 'MCI', ],
            ['name' => 'Orlando International Airport',  'iso_country' => 'US', 'iso_region' => 'US-FL', 'iata_code' => 'MCO', ],
            ['name' => 'Chicago Midway International Airport',  'iso_country' => 'US', 'iso_region' => 'US-IL', 'iata_code' => 'MDW', ],
            ['name' => 'Memphis International Airport',  'iso_country' => 'US', 'iso_region' => 'US-TN', 'iata_code' => 'MEM', ],
            ['name' => 'Dobbins Air Reserve Base',  'iso_country' => 'US', 'iso_region' => 'US-GA', 'iata_code' => 'MGE', ],
            ['name' => 'Montgomery Regional (Dannelly Field) Airport',  'iso_country' => 'US', 'iso_region' => 'US-AL', 'iata_code' => 'MGM', ],
            ['name' => 'Manchester-Boston Regional Airport',  'iso_country' => 'US', 'iso_region' => 'US-NH', 'iata_code' => 'MHT', ],
            ['name' => 'Miami International Airport',  'iso_country' => 'US', 'iso_region' => 'US-FL', 'iata_code' => 'MIA', ],
            ['name' => 'General Mitchell International Airport',  'iso_country' => 'US', 'iso_region' => 'US-WI', 'iata_code' => 'MKE', ],
            ['name' => 'Quad City International Airport',  'iso_country' => 'US', 'iso_region' => 'US-IL', 'iata_code' => 'MLI', ],
            ['name' => 'Monroe Regional Airport',  'iso_country' => 'US', 'iso_region' => 'US-LA', 'iata_code' => 'MLU', ],
            ['name' => 'Mobile Regional Airport',  'iso_country' => 'US', 'iso_region' => 'US-AL', 'iata_code' => 'MOB', ],
            ['name' => 'Dane County Regional Truax Field',  'iso_country' => 'US', 'iso_region' => 'US-WI', 'iata_code' => 'MSN', ],
            ['name' => 'Minneapolis-St Paul International/Wold-Chamberlain Airport',  'iso_country' => 'US', 'iso_region' => 'US-MN', 'iata_code' => 'MSP', ],
            ['name' => 'Louis Armstrong New Orleans International Airport',  'iso_country' => 'US', 'iso_region' => 'US-LA', 'iata_code' => 'MSY', ],
            ['name' => 'Mountain Home Air Force Base',  'iso_country' => 'US', 'iso_region' => 'US-ID', 'iata_code' => 'MUO', ],
            ['name' => 'Metropolitan Oakland International Airport',  'iso_country' => 'US', 'iso_region' => 'US-CA', 'iata_code' => 'OAK', ],
            ['name' => 'Will Rogers World Airport',  'iso_country' => 'US', 'iso_region' => 'US-OK', 'iata_code' => 'OKC', ],
            ['name' => 'Eppley Airfield',  'iso_country' => 'US', 'iso_region' => 'US-NE', 'iata_code' => 'OMA', ],
            ['name' => 'Ontario International Airport',  'iso_country' => 'US', 'iso_region' => 'US-CA', 'iata_code' => 'ONT', ],
            ['name' => 'Chicago O\nHare International Airport',  'iso_country' => 'US', 'iso_region' => 'US-IL', 'iata_code' => 'ORD', ],
            ['name' => 'Norfolk International Airport',  'iso_country' => 'US', 'iso_region' => 'US-VA', 'iata_code' => 'ORF', ],
            ['name' => 'Tyndall Air Force Base',  'iso_country' => 'US', 'iso_region' => 'US-FL', 'iata_code' => 'PAM', ],
            ['name' => 'Palm Beach International Airport',  'iso_country' => 'US', 'iso_region' => 'US-FL', 'iata_code' => 'PBI', ],
            ['name' => 'Portland International Airport',  'iso_country' => 'US', 'iso_region' => 'US-OR', 'iata_code' => 'PDX', ],
            ['name' => 'Newport News Williamsburg International Airport',  'iso_country' => 'US', 'iso_region' => 'US-VA', 'iata_code' => 'PHF', ],
            ['name' => 'Philadelphia International Airport',  'iso_country' => 'US', 'iso_region' => 'US-PA', 'iata_code' => 'PHL', ],
            ['name' => 'Phoenix Sky Harbor International Airport',  'iso_country' => 'US', 'iso_region' => 'US-AZ', 'iata_code' => 'PHX', ],
            ['name' => 'General Wayne A. Downing Peoria International Airport',  'iso_country' => 'US', 'iso_region' => 'US-IL', 'iata_code' => 'PIA', ],
            ['name' => 'Pittsburgh International Airport',  'iso_country' => 'US', 'iso_region' => 'US-PA', 'iata_code' => 'PIT', ],
            ['name' => 'Theodore Francis Green State Airport',  'iso_country' => 'US', 'iso_region' => 'US-RI', 'iata_code' => 'PVD', ],
            ['name' => 'Portland International Jetport',  'iso_country' => 'US', 'iso_region' => 'US-ME', 'iata_code' => 'PWM', ],
            ['name' => 'Raleigh Durham International Airport',  'iso_country' => 'US', 'iso_region' => 'US-NC', 'iata_code' => 'RDU', ],
            ['name' => 'Chicago Rockford International Airport',  'iso_country' => 'US', 'iso_region' => 'US-IL', 'iata_code' => 'RFD', ],
            ['name' => 'Richmond International Airport',  'iso_country' => 'US', 'iso_region' => 'US-VA', 'iata_code' => 'RIC', ],
            ['name' => 'Randolph Air Force Base',  'iso_country' => 'US', 'iso_region' => 'US-TX', 'iata_code' => 'RND', ],
            ['name' => 'Reno Tahoe International Airport',  'iso_country' => 'US', 'iso_region' => 'US-NV', 'iata_code' => 'RNO', ],
            ['name' => 'Roanoke–Blacksburg Regional Airport',  'iso_country' => 'US', 'iso_region' => 'US-VA', 'iata_code' => 'ROA', ],
            ['name' => 'Greater Rochester International Airport',  'iso_country' => 'US', 'iso_region' => 'US-NY', 'iata_code' => 'ROC', ],
            ['name' => 'Rochester International Airport',  'iso_country' => 'US', 'iso_region' => 'US-MN', 'iata_code' => 'RST', ],
            ['name' => 'Southwest Florida International Airport',  'iso_country' => 'US', 'iso_region' => 'US-FL', 'iata_code' => 'RSW', ],
            ['name' => 'San Diego International Airport',  'iso_country' => 'US', 'iso_region' => 'US-CA', 'iata_code' => 'SAN', ],
            ['name' => 'San Antonio International Airport',  'iso_country' => 'US', 'iso_region' => 'US-TX', 'iata_code' => 'SAT', ],
            ['name' => 'Savannah Hilton Head International Airport',  'iso_country' => 'US', 'iso_region' => 'US-GA', 'iata_code' => 'SAV', ],
            ['name' => 'South Bend Regional Airport',  'iso_country' => 'US', 'iso_region' => 'US-IN', 'iata_code' => 'SBN', ],
            ['name' => 'Louisville Muhammad Ali International Airport',  'iso_country' => 'US', 'iso_region' => 'US-KY', 'iata_code' => 'SDF', ],
            ['name' => 'Seattle Tacoma International Airport',  'iso_country' => 'US', 'iso_region' => 'US-WA', 'iata_code' => 'SEA', ],
            ['name' => 'Orlando Sanford International Airport',  'iso_country' => 'US', 'iso_region' => 'US-FL', 'iata_code' => 'SFB', ],
            ['name' => 'San Francisco International Airport',  'iso_country' => 'US', 'iso_region' => 'US-CA', 'iata_code' => 'SFO', ],
            ['name' => 'Springfield Branson National Airport',  'iso_country' => 'US', 'iso_region' => 'US-MO', 'iata_code' => 'SGF', ],
            ['name' => 'Norman Y. Mineta San Jose International Airport',  'iso_country' => 'US', 'iso_region' => 'US-CA', 'iata_code' => 'SJC', ],
            ['name' => 'Fairchild Air Force Base',  'iso_country' => 'US', 'iso_region' => 'US-WA', 'iata_code' => 'SKA', ],
            ['name' => 'Salt Lake City International Airport',  'iso_country' => 'US', 'iso_region' => 'US-UT', 'iata_code' => 'SLC', ],
            ['name' => 'Sacramento International Airport',  'iso_country' => 'US', 'iso_region' => 'US-CA', 'iata_code' => 'SMF', ],
            ['name' => 'John Wayne Airport-Orange County Airport',  'iso_country' => 'US', 'iso_region' => 'US-CA', 'iata_code' => 'SNA', ],
            ['name' => 'Abraham Lincoln Capital Airport',  'iso_country' => 'US', 'iso_region' => 'US-IL', 'iata_code' => 'SPI', ],
            ['name' => 'Sheppard Air Force Base-Wichita Falls Municipal Airport',  'iso_country' => 'US', 'iso_region' => 'US-TX', 'iata_code' => 'SPS', ],
            ['name' => 'Sarasota Bradenton International Airport',  'iso_country' => 'US', 'iso_region' => 'US-FL', 'iata_code' => 'SRQ', ],
            ['name' => 'Shaw Air Force Base',  'iso_country' => 'US', 'iso_region' => 'US-SC', 'iata_code' => 'SSC', ],
            ['name' => 'St Louis Lambert International Airport',  'iso_country' => 'US', 'iso_region' => 'US-MO', 'iata_code' => 'STL', ],
            ['name' => 'Spirit of St Louis Airport',  'iso_country' => 'US', 'iso_region' => 'US-MO', 'iata_code' => 'SUS', ],
            ['name' => 'Travis Air Force Base',  'iso_country' => 'US', 'iso_region' => 'US-CA', 'iata_code' => 'SUU', ],
            ['name' => 'Sioux Gateway Airport/Brigadier General Bud Day Field',  'iso_country' => 'US', 'iso_region' => 'US-IA', 'iata_code' => 'SUX', ],
            ['name' => 'Syracuse Hancock International Airport',  'iso_country' => 'US', 'iso_region' => 'US-NY', 'iata_code' => 'SYR', ],
            ['name' => 'Whiteman Air Force Base',  'iso_country' => 'US', 'iso_region' => 'US-MO', 'iata_code' => 'SZL', ],
            ['name' => 'McChord Air Force Base',  'iso_country' => 'US', 'iso_region' => 'US-WA', 'iata_code' => 'TCM', ],
            ['name' => 'Tinker Air Force Base',  'iso_country' => 'US', 'iso_region' => 'US-OK', 'iata_code' => 'TIK', ],
            ['name' => 'Tallahassee Regional Airport',  'iso_country' => 'US', 'iso_region' => 'US-FL', 'iata_code' => 'TLH', ],
            ['name' => 'Toledo Express Airport',  'iso_country' => 'US', 'iso_region' => 'US-OH', 'iata_code' => 'TOL', ],
            ['name' => 'Tampa International Airport',  'iso_country' => 'US', 'iso_region' => 'US-FL', 'iata_code' => 'TPA', ],
            ['name' => 'Tri-Cities Regional TN/VA Airport',  'iso_country' => 'US', 'iso_region' => 'US-TN', 'iata_code' => 'TRI', ],
            ['name' => 'Tulsa International Airport',  'iso_country' => 'US', 'iso_region' => 'US-OK', 'iata_code' => 'TUL', ],
            ['name' => 'Tucson International Airport / Morris Air National Guard Base',  'iso_country' => 'US', 'iso_region' => 'US-AZ', 'iata_code' => 'TUS', ],
            ['name' => 'McGhee Tyson Airport',  'iso_country' => 'US', 'iso_region' => 'US-TN', 'iata_code' => 'TYS', ],
            ['name' => 'Vandenberg Air Force Base',  'iso_country' => 'US', 'iso_region' => 'US-CA', 'iata_code' => 'VBG', ],
            ['name' => 'Destin-Ft Walton Beach Airport',  'iso_country' => 'US', 'iso_region' => 'US-FL', 'iata_code' => 'VPS', ],
            ['name' => 'Robins Air Force Base',  'iso_country' => 'US', 'iso_region' => 'US-GA', 'iata_code' => 'WRB', ],
            ['name' => 'Tirana International Airport Mother Teresa',  'iso_country' => 'AL', 'iso_region' => 'AL-11', 'iata_code' => 'TIA', ],
            ['name' => 'Burgas Airport',  'iso_country' => 'BG', 'iso_region' => 'BG-02', 'iata_code' => 'BOJ', ],
            ['name' => 'Sofia Airport',  'iso_country' => 'BG', 'iso_region' => 'BG-23', 'iata_code' => 'SOF', ],
            ['name' => 'Varna Airport',  'iso_country' => 'BG', 'iso_region' => 'BG-03', 'iata_code' => 'VAR', ],
            ['name' => 'RAF Akrotiri',  'iso_country' => 'GB', 'iso_region' => 'GB-U-A', 'iata_code' => 'AKT', ],
            ['name' => 'Zagreb Airport',  'iso_country' => 'HR', 'iso_region' => 'HR-21', 'iata_code' => 'ZAG', ],
            ['name' => 'Alicante International Airport',  'iso_country' => 'ES', 'iso_region' => 'ES-V', 'iata_code' => 'ALC', ],
            ['name' => 'Barcelona International Airport',  'iso_country' => 'ES', 'iso_region' => 'ES-CT', 'iata_code' => 'BCN', ],
            ['name' => 'Adolfo Suárez Madrid–Barajas Airport',  'iso_country' => 'ES', 'iso_region' => 'ES-M', 'iata_code' => 'MAD', ],
            ['name' => 'Málaga Airport',  'iso_country' => 'ES', 'iso_region' => 'ES-AN', 'iata_code' => 'AGP', ],
            ['name' => 'Palma De Mallorca Airport',  'iso_country' => 'ES', 'iso_region' => 'ES-PM', 'iata_code' => 'PMI', ],
            ['name' => 'Santiago de Compostela Airport',  'iso_country' => 'ES', 'iso_region' => 'ES-GA', 'iata_code' => 'SCQ', ],
            ['name' => 'Bordeaux-Mérignac Airport',  'iso_country' => 'FR', 'iso_region' => 'FR-NAQ', 'iata_code' => 'BOD', ],
            ['name' => 'Toulouse-Blagnac Airport',  'iso_country' => 'FR', 'iso_region' => 'FR-OCC', 'iata_code' => 'TLS', ],
            ['name' => 'Lyon Saint-Exupéry Airport',  'iso_country' => 'FR', 'iso_region' => 'FR-ARA', 'iata_code' => 'LYS', ],
            ['name' => 'Marseille Provence Airport',  'iso_country' => 'FR', 'iso_region' => 'FR-PAC', 'iata_code' => 'MRS', ],
            ['name' => 'Nice-Côte d\nAzur Airport',  'iso_country' => 'FR', 'iso_region' => 'FR-PAC', 'iata_code' => 'NCE', ],
            ['name' => 'Charles de Gaulle International Airport',  'iso_country' => 'FR', 'iso_region' => 'FR-IDF', 'iata_code' => 'CDG', ],
            ['name' => 'Paris-Orly Airport',  'iso_country' => 'FR', 'iso_region' => 'FR-IDF', 'iata_code' => 'ORY', ],
            ['name' => 'EuroAirport Basel-Mulhouse-Freiburg Airport',  'iso_country' => 'FR', 'iso_region' => 'FR-GES', 'iata_code' => 'BSL', ],
            ['name' => 'Eleftherios Venizelos International Airport',  'iso_country' => 'GR', 'iso_region' => 'GR-A1', 'iata_code' => 'ATH', ],
            ['name' => 'Heraklion International Nikos Kazantzakis Airport',  'iso_country' => 'GR', 'iso_region' => 'GR-91', 'iata_code' => 'HER', ],
            ['name' => 'Thessaloniki Macedonia International Airport',  'iso_country' => 'GR', 'iso_region' => 'GR-54', 'iata_code' => 'SKG', ],
            ['name' => 'Budapest Liszt Ferenc International Airport',  'iso_country' => 'HU', 'iso_region' => 'HU-PE', 'iata_code' => 'BUD', ],
            ['name' => 'Bari Karol Wojtyła Airport',  'iso_country' => 'IT', 'iso_region' => 'IT-75', 'iata_code' => 'BRI', ],
            ['name' => 'Catania-Fontanarossa Airport',  'iso_country' => 'IT', 'iso_region' => 'IT-82', 'iata_code' => 'CTA', ],
            ['name' => 'Falcone–Borsellino Airport',  'iso_country' => 'IT', 'iso_region' => 'IT-82', 'iata_code' => 'PMO', ],
            ['name' => 'Cagliari Elmas Airport',  'iso_country' => 'IT', 'iso_region' => 'IT-88', 'iata_code' => 'CAG', ],
            ['name' => 'Malpensa International Airport',  'iso_country' => 'IT', 'iso_region' => 'IT-25', 'iata_code' => 'MXP', ],
            ['name' => 'Milan Bergamo Airport',  'iso_country' => 'IT', 'iso_region' => 'IT-25', 'iata_code' => 'BGY', ],
            ['name' => 'Turin Airport',  'iso_country' => 'IT', 'iso_region' => 'IT-21', 'iata_code' => 'TRN', ],
            ['name' => 'Genoa Cristoforo Colombo Airport',  'iso_country' => 'IT', 'iso_region' => 'IT-42', 'iata_code' => 'GOA', ],
            ['name' => 'Milano Linate Airport',  'iso_country' => 'IT', 'iso_region' => 'IT-25', 'iata_code' => 'LIN', ],
            ['name' => 'Bologna Guglielmo Marconi Airport',  'iso_country' => 'IT', 'iso_region' => 'IT-45', 'iata_code' => 'BLQ', ],
            ['name' => 'Treviso-Sant\nAngelo Airport',  'iso_country' => 'IT', 'iso_region' => 'IT-34', 'iata_code' => 'TSF', ],
            ['name' => 'Verona Villafranca Airport',  'iso_country' => 'IT', 'iso_region' => 'IT-34', 'iata_code' => 'VRN', ],
            ['name' => 'Venice Marco Polo Airport',  'iso_country' => 'IT', 'iso_region' => 'IT-34', 'iata_code' => 'VCE', ],
            ['name' => 'Ciampino–G. B. Pastine International Airport',  'iso_country' => 'IT', 'iso_region' => 'IT-62', 'iata_code' => 'CIA', ],
            ['name' => 'Leonardo da Vinci–Fiumicino Airport',  'iso_country' => 'IT', 'iso_region' => 'IT-62', 'iata_code' => 'FCO', ],
            ['name' => 'Naples International Airport',  'iso_country' => 'IT', 'iso_region' => 'IT-72', 'iata_code' => 'NAP', ],
            ['name' => 'Pisa International Airport',  'iso_country' => 'IT', 'iso_region' => 'IT-52', 'iata_code' => 'PSA', ],
            ['name' => 'Ljubljana Jože Pučnik Airport',  'iso_country' => 'SI', 'iso_region' => 'SI-061', 'iata_code' => 'LJU', ],
            ['name' => 'Václav Havel Airport Prague',  'iso_country' => 'CZ', 'iso_region' => 'CZ-PR', 'iata_code' => 'PRG', ],
            ['name' => 'Malta International Airport',  'iso_country' => 'MT', 'iso_region' => 'MT-25', 'iata_code' => 'MLA', ],
            ['name' => 'Vienna International Airport',  'iso_country' => 'AT', 'iso_region' => 'AT-9', 'iata_code' => 'VIE', ],
            ['name' => 'Faro Airport',  'iso_country' => 'PT', 'iso_region' => 'PT-08', 'iata_code' => 'FAO', ],
            ['name' => 'Lajes Airport',  'iso_country' => 'PT', 'iso_region' => 'PT-20', 'iata_code' => 'TER', ],
            ['name' => 'João Paulo II Airport',  'iso_country' => 'PT', 'iso_region' => 'PT-20', 'iata_code' => 'PDL', ],
            ['name' => 'Francisco de Sá Carneiro Airport',  'iso_country' => 'PT', 'iso_region' => 'PT-13', 'iata_code' => 'OPO', ],
            ['name' => 'Humberto Delgado Airport (Lisbon Portela Airport)',  'iso_country' => 'PT', 'iso_region' => 'PT-11', 'iata_code' => 'LIS', ],
            ['name' => 'Sarajevo International Airport',  'iso_country' => 'BA', 'iso_region' => 'BA-BIH', 'iata_code' => 'SJJ', ],
            ['name' => 'Henri Coandă International Airport',  'iso_country' => 'RO', 'iso_region' => 'RO-B', 'iata_code' => 'OTP', ],
            ['name' => 'Geneva Cointrin International Airport',  'iso_country' => 'CH', 'iso_region' => 'CH-GE', 'iata_code' => 'GVA', ],
            ['name' => 'Zürich Airport',  'iso_country' => 'CH', 'iso_region' => 'CH-ZH', 'iata_code' => 'ZRH', ],
            ['name' => 'Skopje International Airport',  'iso_country' => 'MK', 'iso_region' => 'MK-004', 'iata_code' => 'SKP', ],
            ['name' => 'Belgrade Nikola Tesla Airport',  'iso_country' => 'RS', 'iso_region' => 'RS-00', 'iata_code' => 'BEG', ],
            ['name' => 'Podgorica Airport',  'iso_country' => 'ME', 'iso_region' => 'ME-16', 'iata_code' => 'TGD', ],
            ['name' => 'M. R. Štefánik Airport',  'iso_country' => 'SK', 'iso_region' => 'SK-BL', 'iata_code' => 'BTS', ],
            ['name' => 'Punta Cana International Airport',  'iso_country' => 'DO', 'iso_region' => 'DO-11', 'iata_code' => 'PUJ', ],
            ['name' => 'Las Américas International Airport',  'iso_country' => 'DO', 'iso_region' => 'DO-01', 'iata_code' => 'SDQ', ],
            ['name' => 'La Aurora Airport',  'iso_country' => 'GT', 'iso_region' => 'GT-GU', 'iata_code' => 'GUA', ],
            ['name' => 'Norman Manley International Airport',  'iso_country' => 'JM', 'iso_region' => 'JM-01', 'iata_code' => 'KIN', ],
            ['name' => 'General Juan N Alvarez International Airport',  'iso_country' => 'MX', 'iso_region' => 'MX-GRO', 'iata_code' => 'ACA', ],
            ['name' => 'Don Miguel Hidalgo Y Costilla International Airport',  'iso_country' => 'MX', 'iso_region' => 'MX-JAL', 'iata_code' => 'GDL', ],
            ['name' => 'General Ignacio P. Garcia International Airport',  'iso_country' => 'MX', 'iso_region' => 'MX-SON', 'iata_code' => 'HMO', ],
            ['name' => 'Licenciado Benito Juarez International Airport',  'iso_country' => 'MX', 'iso_region' => 'MX-DIF', 'iata_code' => 'MEX', ],
            ['name' => 'General Mariano Escobedo International Airport',  'iso_country' => 'MX', 'iso_region' => 'MX-NLE', 'iata_code' => 'MTY', ],
            ['name' => 'Licenciado Gustavo Díaz Ordaz International Airport',  'iso_country' => 'MX', 'iso_region' => 'MX-JAL', 'iata_code' => 'PVR', ],
            ['name' => 'Los Cabos International Airport',  'iso_country' => 'MX', 'iso_region' => 'MX-BCS', 'iata_code' => 'SJD', ],
            ['name' => 'General Abelardo L. Rodríguez International Airport',  'iso_country' => 'MX', 'iso_region' => 'MX-BCN', 'iata_code' => 'TIJ', ],
            ['name' => 'Cancún International Airport',  'iso_country' => 'MX', 'iso_region' => 'MX-ROO', 'iata_code' => 'CUN', ],
            ['name' => 'Tocumen International Airport',  'iso_country' => 'PA', 'iso_region' => 'PA-8', 'iata_code' => 'PTY', ],
            ['name' => 'Daniel Oduber Quiros International Airport',  'iso_country' => 'CR', 'iso_region' => 'CR-G', 'iata_code' => 'LIR', ],
            ['name' => 'Monseñor Óscar Arnulfo Romero International Airport',  'iso_country' => 'SV', 'iso_region' => 'SV-PA', 'iata_code' => 'SAL', ],
            ['name' => 'José Martí International Airport',  'iso_country' => 'CU', 'iso_region' => 'CU-03', 'iata_code' => 'HAV', ],
            ['name' => 'Juan Gualberto Gomez International Airport',  'iso_country' => 'CU', 'iso_region' => 'CU-04', 'iata_code' => 'VRA', ],
            ['name' => 'Owen Roberts International Airport',  'iso_country' => 'KY', 'iso_region' => 'KY-U-A', 'iata_code' => 'GCM', ],
            ['name' => 'Lynden Pindling International Airport',  'iso_country' => 'BS', 'iso_region' => 'BS-NP', 'iata_code' => 'NAS', ],
            ['name' => 'Philip S. W. Goldson International Airport',  'iso_country' => 'BZ', 'iso_region' => 'BZ-BZ', 'iata_code' => 'BZE', ],
            ['name' => 'Fairbanks International Airport',  'iso_country' => 'US', 'iso_region' => 'US-AK', 'iata_code' => 'FAI', ],
            ['name' => 'Ted Stevens Anchorage International Airport',  'iso_country' => 'US', 'iso_region' => 'US-AK', 'iata_code' => 'ANC', ],
            ['name' => 'Daniel K Inouye International Airport',  'iso_country' => 'US', 'iso_region' => 'US-HI', 'iata_code' => 'HNL', ],
            ['name' => 'Grozny North Airport',  'iso_country' => 'RU', 'iso_region' => 'RU-CE', 'iata_code' => 'GRV', ],
            ['name' => 'Ministro Pistarini International Airport',  'iso_country' => 'AR', 'iso_region' => 'AR-B', 'iata_code' => 'EZE', ],
            ['name' => 'Val de Cans/Júlio Cezar Ribeiro International Airport',  'iso_country' => 'BR', 'iso_region' => 'BR-PA', 'iata_code' => 'BEL', ],
            ['name' => 'Presidente Juscelino Kubitschek International Airport',  'iso_country' => 'BR', 'iso_region' => 'BR-DF', 'iata_code' => 'BSB', ],
            ['name' => 'Tancredo Neves International Airport',  'iso_country' => 'BR', 'iso_region' => 'BR-MG', 'iata_code' => 'CNF', ],
            ['name' => 'Afonso Pena Airport',  'iso_country' => 'BR', 'iso_region' => 'BR-PR', 'iata_code' => 'CWB', ],
            ['name' => 'Eduardo Gomes International Airport',  'iso_country' => 'BR', 'iso_region' => 'BR-AM', 'iata_code' => 'MAO', ],
            ['name' => 'Hercílio Luz International Airport',  'iso_country' => 'BR', 'iso_region' => 'BR-SC', 'iata_code' => 'FLN', ],
            ['name' => 'Rio Galeão – Tom Jobim International Airport',  'iso_country' => 'BR', 'iso_region' => 'BR-RJ', 'iata_code' => 'GIG', ],
            ['name' => 'Guarulhos - Governador André Franco Montoro International Airport',  'iso_country' => 'BR', 'iso_region' => 'BR-SP', 'iata_code' => 'GRU', ],
            ['name' => 'Governador Aluízio Alves International Airport',  'iso_country' => 'BR', 'iso_region' => 'BR-RN', 'iata_code' => 'NAT', ],
            ['name' => 'Congonhas Airport',  'iso_country' => 'BR', 'iso_region' => 'BR-SP', 'iata_code' => 'CGH', ],
            ['name' => 'Deputado Luiz Eduardo Magalhães International Airport',  'iso_country' => 'BR', 'iso_region' => 'BR-BA', 'iata_code' => 'SSA', ],
            ['name' => 'Comodoro Arturo Merino Benítez International Airport',  'iso_country' => 'CL', 'iso_region' => 'CL-RM', 'iata_code' => 'SCL', ],
            ['name' => 'Cotopaxi International Airport',  'iso_country' => 'EC', 'iso_region' => 'EC-X', 'iata_code' => 'LTX', ],
            ['name' => 'Mariscal Sucre International Airport',  'iso_country' => 'EC', 'iso_region' => 'EC-P', 'iata_code' => 'UIO', ],
            ['name' => 'El Dorado International Airport',  'iso_country' => 'CO', 'iso_region' => 'CO-CUN', 'iata_code' => 'BOG', ],
            ['name' => 'Viru Viru International Airport',  'iso_country' => 'BO', 'iso_region' => 'BO-S', 'iata_code' => 'VVI', ],
            ['name' => 'Jorge Chávez International Airport',  'iso_country' => 'PE', 'iso_region' => 'PE-LIM', 'iata_code' => 'LIM', ],
            ['name' => 'Alejandro Velasco Astete International Airport',  'iso_country' => 'PE', 'iso_region' => 'PE-CUS', 'iata_code' => 'CUZ', ],
            ['name' => 'Carrasco International /General C L Berisso Airport',  'iso_country' => 'UY', 'iso_region' => 'UY-CA', 'iata_code' => 'MVD', ],
            ['name' => 'General José Antonio Anzoategui International Airport',  'iso_country' => 'VE', 'iso_region' => 'VE-B', 'iata_code' => 'BLA', ],
            ['name' => 'Simón Bolívar International Airport',  'iso_country' => 'VE', 'iso_region' => 'VE-X', 'iata_code' => 'CCS', ],
            ['name' => 'Pointe-à-Pitre Le Raizet',  'iso_country' => 'GP', 'iso_region' => 'GP-U-A', 'iata_code' => 'PTP', ],
            ['name' => 'Luis Munoz Marin International Airport',  'iso_country' => 'PR', 'iso_region' => 'PR-U-A', 'iata_code' => 'SJU', ],
            ['name' => 'Princess Juliana International Airport',  'iso_country' => 'SX', 'iso_region' => 'SX-U-A', 'iata_code' => 'SXM', ],
            ['name' => 'Boryspil International Airport',  'iso_country' => 'UA', 'iso_region' => 'UA-32', 'iata_code' => 'KBP', ],
            ['name' => 'Simferopol International Airport',  'iso_country' => 'UA', 'iso_region' => 'UA-43', 'iata_code' => 'SIP', ],
            ['name' => 'Kharkiv International Airport',  'iso_country' => 'UA', 'iso_region' => 'UA-63', 'iata_code' => 'HRK', ],
            ['name' => 'Odessa International Airport',  'iso_country' => 'UA', 'iso_region' => 'UA-51', 'iata_code' => 'ODS', ],
            ['name' => 'Pulkovo Airport',  'iso_country' => 'RU', 'iso_region' => 'RU-SPE', 'iata_code' => 'LED', ],
            ['name' => 'Minsk National Airport',  'iso_country' => 'BY', 'iso_region' => 'BY-MI', 'iata_code' => 'MSQ', ],
            ['name' => 'Yemelyanovo Airport',  'iso_country' => 'RU', 'iso_region' => 'RU-KYA', 'iata_code' => 'KJA', ],
            ['name' => 'Platov International Airport',  'iso_country' => 'RU', 'iso_region' => 'RU-ROS', 'iata_code' => 'ROV', ],
            ['name' => 'Sochi International Airport',  'iso_country' => 'RU', 'iso_region' => 'RU-KDA', 'iata_code' => 'AER', ],
            ['name' => 'Zhukovsky International Airport',  'iso_country' => 'RU', 'iso_region' => 'RU-MOS', 'iata_code' => 'ZIA', ],
            ['name' => 'Domodedovo International Airport',  'iso_country' => 'RU', 'iso_region' => 'RU-MOS', 'iata_code' => 'DME', ],
            ['name' => 'Sheremetyevo International Airport',  'iso_country' => 'RU', 'iso_region' => 'RU-MOS', 'iata_code' => 'SVO', ],
            ['name' => 'Vnukovo International Airport',  'iso_country' => 'RU', 'iso_region' => 'RU-MOS', 'iata_code' => 'VKO', ],
            ['name' => 'Kazan International Airport',  'iso_country' => 'RU', 'iso_region' => 'RU-TA', 'iata_code' => 'KZN', ],
            ['name' => 'Ufa International Airport',  'iso_country' => 'RU', 'iso_region' => 'RU-BA', 'iata_code' => 'UFA', ],
            ['name' => 'Kurumoch International Airport',  'iso_country' => 'RU', 'iso_region' => 'RU-SAM', 'iata_code' => 'KUF', ],
        ];
        $countries = DB::table('countries')->get();
        foreach ($airports as $airport){
            $airport['country_id'] = null;
            foreach ($countries as $country){
                if ($country->code == $airport['iso_country']){
                    $airport['country_id'] = $country->id;
                }
            }
           Airport::query()->create($airport);
        }
    }
}
